version: 2
jobs:
  build:
    branches:
            - master
    docker:
            - image: fedora:latest
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Current Time
          command: date
      - run:
          name: Listing directory
          command: pwd && ls -lah 
      - run:
          name: Installing Dependencies
          command: dnf install git -y    
      - run:
          name: Automatic deploy
          command: git checkout -b gh-pages; rm -r README.md .circleci; mv src/* .; rm -r src/* .; rm -r src; git add .; git commit -m ":trollface: Deploy from circleci $(date)"; git push -f origin gh-pages; echo "running..."
